### PR TITLE
Fix label of inline links not set correctly

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Closes https://github.com/lunet-io/markdig/issues/487

I'm new to the code base, so I have no idea if this is the right approach. It does fix the issue. I didn't know where to add a test for this. Let me know if you'd like me to add such a test.

### CODE REVIEW

**Comment by xoofx** [comment]
Could you add a small `TestLinkParser.cs` with a test extracted from the issue #487?

**Comment by ErikSchierboom** [comment]
@xoofx Sure! My pleasure.

**Comment by ErikSchierboom** [comment]
@xoofx I've found an issue with my implementation, so it could take a little longer!

**Comment by ErikSchierboom** [comment]
@xoofx Apparently I've misread the spec 🤦 The Label is used for the reference definition linking.

After some trial and error, I've found that I can get the link text using the following method (having enabled precise source location):

```csharp
string GetIdentifier(LinkInline link, string markdown)
{
    if (link.IsShortcut)
    {
         return link.Label;
    }

    return markdown[link.FirstChild.Span.Start..(link.LastChild.Span.End + 1)];
}
```

Do you think there is any value in adding a `TextSpan` property to the `LinkInline` class to allow the above code to be simplified:

```csharp
string GetIdentifier(LinkInline link, string markdown)
{
    return markdown[link.TextSpan.Start..(link.TextSpan.End + 1)];
}
```

Let me know what you think. If you don't think this is valuable, feel free to close this issue.

**Pull request closed without merging**
