### PR TITLE
Enable ImplictUsings and use file-scoped namespaces

### PR DESCRIPTION
**Pull request by iamcarbon**
This PR is up for feedback on whether we should enable file-scoped namespaces on some of all of the markdig projects.

Pulling the indentation in 4 lines on the tests is a fairly nice improvement for readability -- particularly on a 15" laptop.

### CODE REVIEW

**Comment by iamcarbon** [comment]
@MihaZupan @xoofx Let me know what you think. If we do make this change on the main library -- it would make the change history harder to follow -- but improve the experience working with those files moving forward.

**Comment by xoofx** [comment]
> @MihaZupan @xoofx Let me know what you think. If we do make this change on the main library -- it would make the change history harder to follow -- but improve the experience working with those files moving forward.

Yeah, please go ahead in applying this to the rest of the library, it should be ok. Thanks!

**Comment by MihaZupan** [comment]
I like the feature, thanks!
My only concern is the quality of the automatic refactoring - when we did this in YARP it messed up indentation in random places. We should just double-check that doesn't happen before merging.

**Comment by iamcarbon** [comment]
@MihaZupan Agreed on the caution -- I used the refactoring tools to do this file by file, checking them as I went along to make sure everything was indented correctly. We should be OK!

**Comment by iamcarbon** [comment]
@xoofx @MihaZupan Ready for review. I also fixed a couple spelling errors in the comments while I was double checking the indentation levels.

**Comment by iamcarbon** [comment]
Here's a direct link to review ignoring whitespace changes: https://github.com/xoofx/markdig/pull/693/files?diff=unified&w=1

**Comment by xoofx** [comment]
Thanks a lot!

**Pull request merged**
