### PR TITLE
ignore whitespace at end of pipe table row header

### LINKED ISSUE #535: A bug in table parsing in v0.24
A found an issue when I upgraded to v0.24 - v0.23 works fine. I parse MarkDown files and look for tables. In some cases, the parser missed the last table in a document. I narrowed it down to the following,

```
        [Test]
        public void TestTableBug()
        {
            const string testData = @"
| S | 
|---|
| G |

| D | D |
|---|---| 
| V | V |";
            MarkdownDocument document = Markdown.Parse(testData, new MarkdownPipelineBuilder().UseAdvancedExtensions().Build());

            Table[] tables = document.Descendants().OfType<Table>().ToArray();

            Assert.AreEqual(2, tables.Length, "Did you upgrade to MarkDig > 0.23?");
        }
```

### PR DESCRIPTION
**Pull request by generateui**
Fixes #535.

### CODE REVIEW

**Comment by xoofx** [comment]
NuGet restore is broken (not your fault), not sure why.

**Comment by MihaZupan** [comment]
Probably https://github.com/actions/virtual-environments/issues/3038 - NuGet restore issue on windows environments.

Apparently manually adding the nuget feed is a workaround? https://github.com/actions/setup-dotnet/issues/155#issuecomment-761195782

**Comment by xoofx** [comment]
> Probably [actions/virtual-environments#3038](https://github.com/actions/virtual-environments/issues/3038) - NuGet restore issue on windows environments.
> 
> Apparently manually adding the nuget feed is a workaround? [actions/setup-dotnet#155 (comment)](https://github.com/actions/setup-dotnet/issues/155#issuecomment-761195782)

Oh, right, good catch! I can see that it might be fixed by https://github.com/actions/virtual-environments/pull/3144 but it will take a few days to rollout.

**Comment by MihaZupan** [comment]
I re-ran the action, seems to be good (at least for this run)

**Comment by xoofx** [comment]
Thanks!

**Comment by generateui** [comment]
👍

**Pull request merged**
