### PR TITLE
Drop .netcoreapp2.1 target and cross target .net6.0

### PR DESCRIPTION
**Pull request by iamcarbon**
.NETCOREAPP2.1 is no longer supported & .NET6.0 will provide us with with 3 years of support.

### CODE REVIEW

**Comment by xoofx** [comment]
Many errors in the logs about:

```
The type 'MemberNotNullAttribute' in 'D:\a\markdig\markdig\src\Markdig\Polyfills\NullableAttributes.cs' conflicts with the imported type 'MemberNotNullAttribute' in 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Using the type defined in 'D:\a\markdig\markdig\src\Markdig\Polyfills\NullableAttributes.cs'.
```

Probably a define not working correctly to exclude it for .NET 6.0

**Comment by iamcarbon** [comment]
@xoofx Addressed. Ready for review.

**Review by MihaZupan — APPROVED** [review]
good riddance

**Comment by xoofx** [comment]
Thanks!

**Pull request merged**
